name: lncm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.12.0=pyhcf101f3_0
  - aom=3.9.1=he0c23c2_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h3485c13_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h06c2b12_7
  - aws-c-cal=0.9.10=ha82e055_1
  - aws-c-common=0.12.5=hfd05255_1
  - aws-c-compression=0.3.1=h83e01e5_8
  - aws-c-event-stream=0.5.6=h3116ff1_6
  - aws-c-http=0.10.7=h52d8906_4
  - aws-c-io=0.23.3=h6f46d10_3
  - aws-c-mqtt=0.13.3=h9821516_10
  - aws-c-s3=0.10.1=he380ad5_2
  - aws-c-sdkutils=0.2.4=h83e01e5_3
  - aws-checksums=0.2.7=h83e01e5_4
  - aws-crt-cpp=0.35.2=h1a9a3a2_4
  - aws-sdk-cpp=1.11.606=h6446450_7
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - blosc=1.21.6=hfd34d9b_1
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - brotli-python=1.2.0=py311h69b5583_0
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.5=h2466b09_0
  - c-blosc2=2.22.0=h3cf07e4_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311h3485c13_1
  - charls=2.4.2=h1537add_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h3fd045d_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ffmpeg=8.0.0=gpl_he3062b8_906
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py311h3f79411_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - gdk-pixbuf=2.44.4=h1f5b9c4_0
  - geos=3.14.1=hdade9fe_0
  - giflib=5.2.2=h64bf75a_0
  - glib=2.86.2=hde84fb4_0
  - glib-tools=2.86.2=he647baa_0
  - glslang=16.0.0=h5b34520_0
  - graphite2=1.3.14=hac47afa_2
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=nompi_py311hc40ba4b_100
  - harfbuzz=12.2.0=h5f2951f_0
  - hdf5=1.14.6=nompi_he30205f_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs=2025.11.11=py311haf4ede9_0
  - imageio=2.37.0=pyhfb79c49_0
  - imath=3.2.2=h1608b31_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jasper=4.2.8=h8ad263b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h1ea47a8_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - jxrlib=1.1=hcfcfb64_3
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.9=py311h275cad7_2
  - krb5=1.21.3=hdf4eb48_0
  - lame=3.100=hcfcfb64_1003
  - lark=1.3.1=pyhd8ed1ab_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.4=h20038f6_0
  - libarrow=22.0.0=h117da51_4_cpu
  - libarrow-acero=22.0.0=h7d8d6a5_4_cpu
  - libarrow-compute=22.0.0=h2db994a_4_cpu
  - libarrow-dataset=22.0.0=h7d8d6a5_4_cpu
  - libarrow-substrait=22.0.0=hf865cc0_4_cpu
  - libasprintf=0.22.5=h5728263_3
  - libavif16=1.3.0=he916da2_2
  - libblas=3.11.0=2_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.11.0=2_h2a3cdd5_mkl
  - libclang13=21.1.6=default_ha2db4b5_0
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libgettextpo=0.22.5=h5728263_3
  - libglib=2.86.2=hd9c3897_0
  - libgomp=15.2.0=h1383e82_7
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.1=hac9b6f3_5
  - liblapack=3.11.0=2_hf9ab0e9_mkl
  - liblapacke=3.11.0=2_h3ae206f_mkl
  - liblzma=5.8.1=h2466b09_2
  - libogg=1.3.5=h2466b09_1
  - libopencv=4.12.0=qt6_py311hf6c31d6_607
  - libopenvino=2025.2.0=hbf28c98_1
  - libopenvino-auto-batch-plugin=2025.2.0=hdd9a157_1
  - libopenvino-auto-plugin=2025.2.0=hdd9a157_1
  - libopenvino-hetero-plugin=2025.2.0=hc39e7c6_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hbf28c98_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hbf28c98_1
  - libopenvino-ir-frontend=2025.2.0=hc39e7c6_1
  - libopenvino-onnx-frontend=2025.2.0=hee3bb10_1
  - libopenvino-paddle-frontend=2025.2.0=hee3bb10_1
  - libopenvino-pytorch-frontend=2025.2.0=hac47afa_1
  - libopenvino-tensorflow-frontend=2025.2.0=h293fe96_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hac47afa_1
  - libopus=1.5.2=h2466b09_0
  - libparquet=22.0.0=h7051d1f_4_cpu
  - libpng=1.6.51=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_2
  - libre2-11=2025.11.05=h0eb2380_0
  - librsvg=2.60.0=hd5e4115_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h8f73337_1
  - libusb=1.0.29=h1839187_0
  - libutf8proc=2.11.1=hb980946_0
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - libzopfli=1.0.3=h0e60522_0
  - llvm-openmp=21.1.6=h4fa8253_0
  - llvmlite=0.45.1=py311h4f568be_0
  - lsq-ellipse=2.2.1=pyhd8ed1ab_0
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib=3.10.8=py311h1ea47a8_0
  - matplotlib-base=3.10.8=py311h1675fdf_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2025.3.0=hac47afa_454
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6=pyhcf101f3_0
  - notebook=7.5.0=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.62.1=py311hffedbe7_0
  - numpy=2.3.5=py311h80b3fa1_0
  - oasis=1.0.2=pyh59e0f4d_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - opencv=4.12.0=qt6_py311h19c12f8_607
  - openexr=3.4.4=ha75af49_0
  - openh264=2.6.0=hb17fa0b_0
  - openjpeg=2.5.4=h24db6dd_0
  - openjph=0.25.3=hf13a347_0
  - openpyxl=3.1.5=py311h4d8bf61_2
  - openssl=3.6.0=h725018a_0
  - orc=2.2.1=h7414dfc_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_1
  - pandas-stubs=2.3.2.250926=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=h03d888a_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pillow=12.0.0=py311hf7ee305_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - ply=3.11=pyhd8ed1ab_3
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.1.3=py311hf893f09_0
  - pthread-stubs=0.4=h0e40799_1002
  - pugixml=1.15=h372dad0_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.12.0=qt6_py311hf16eb4e_607
  - pyarrow=22.0.0=py311h1ea47a8_0
  - pyarrow-core=22.0.0=py311ha836b3b_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pyedflib=0.1.42=py311h17033d2_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=5.15.11=py311h7c55f98_2
  - pyqt5-sip=12.17.0=py311h3e6a449_2
  - pyqtgraph=0.14.0=pyhd8ed1ab_0
  - pyside6=6.9.3=py311hf70c7b4_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.14=h0159041_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.9.0=py311h17033d2_2
  - pywin32=311=py311hefeebc8_1
  - pywinpty=2.0.15=py311hda3d55a_1
  - pyyaml=6.0.3=py311h3f79411_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.15=hb098fff_6
  - qt6-main=6.9.3=ha0de62e_1
  - qt6-multimedia=6.9.3=h314a308_0
  - rav1e=0.7.1=ha073cba_3
  - re2=2025.11.05=ha104f34_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py311hf51aa87_0
  - scikit-image=0.25.2=py311h11fd7f3_2
  - scikit-learn=1.7.2=py311h8a15ebc_0
  - sdl2=2.32.56=h5112557_0
  - sdl3=3.2.26=h5112557_0
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=haa9a63f_0
  - shapely=2.1.2=py311h362461e_2
  - sip=6.10.0=py311h3e6a449_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - spirv-tools=2025.4=h49e36cd_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py311h17033d2_1
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2022.3.0=hd094cb3_1
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.10.16=pyhd8ed1ab_0
  - tinycss2=1.5.0=pyhcf101f3_0
  - tk=8.6.13=h2c6b04d_3
  - toml=0.10.2=pyhd8ed1ab_2
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py311h3485c13_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-pytz=2025.2.0.20251108=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py311h3485c13_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xlrd=2.0.2=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zfp=1.0.1=h2f0f97f_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=h32d8bfd_0
  - zstandard=0.25.0=py311hf893f09_1
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - scipy==1.16.3
      - scipy-stubs==1.16.3.1
prefix: N:\envs\Barna\envs\lncm
